- src/base/AppContext.ts
- src/base/event.ts
- src/i18n/I18nextManager.ts
- src/idtype/IDTypeManager.ts
- src/plugin/PluginRegistry.ts
- src/security/UserSession.ts
migrated all functions of the classes including getInstance to arrow functions to avoid this-overwriting
> Arrow function migration

- src/demo/MainApp.tsx
- src/ranking/EagerVisynRanking.tsx
- src/ranking/VisynRanking.tsx
Makes the VisynRanking lazy to code-split the lineup and scss (therefore fontawesome) imports.
> Make VisynRanking lazy

- src/app/VisynApp.tsx
Closes https://github.com/datavisyn/visyn_core/issues/5
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Set the min height to '100%' instead of '100vh'
- These change should have no side-ffects
-  
> Fix VisynApp bug

- MANIFEST.in
- README.md
- package.json
- src/app/VisynApp.tsx
- src/base/clientConfig.ts
- src/demo/MainApp.tsx
- src/ranking/EagerVisynRanking.tsx
- src/ranking/VisynRanking.tsx
- src/security/LoginUtils.ts
- src/security/watcher.ts
- visyn_core/__init__.py
- visyn_core/settings/model.py
- visyn_core/settings/router.py
- visyn_core/tests/test_settings.py
* Add api/clientConfig to more easily configure the clientConfig #8
* Make VisynRanking lazy #4
In case of dependent Phovea/TDP repositories follow [dependency tree](https://wiki.datavisyn.io/phovea/fundamentals/development-process#dependency-hierarchy) from the top.
> Release v1.1.0

- src/app/login/VisynLoginForm.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add `data-cy` attributes to `VisynLoginForm.tsx`
-  N/A
> fix: add data-cy to login username, password and submit

- package.json
- src/app/login/VisynLoginForm.tsx
* fix: add data-cy to login username, password and submit (https://github.com/datavisyn/visyn_core/pull/16)
In case of dependent Phovea/TDP repositories follow [dependency tree](https://wiki.datavisyn.io/phovea/fundamentals/development-process#dependency-hierarchy) from the top:
> Release 1.1.1

- visyn_core/server/visyn_server.py
- visyn_core/settings/model.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds `visyn_core.cypress` setting to be set by applications in testing mode. Will enable backend adaptions based on this flag.
-  
> Add cypress setting to visyn_core for backend adaptions

- src/hooks/index.tsx
- src/hooks/useEvent.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds `useEvent` hook to allow wrapping of callbacks and receiving a stable reference without the need for `useCallback`. 
-  
> feat: add `useEvent` hook

- src/app/header/AboutAppModal.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add build date from environment variable if available
---  
> feat: add build date to about dialog

- src/app/header/VisynHeader.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The border is causing a weired artifact on the Ordino tabs (since the border color is equal to the background color)
- I think we could remove the border entirely since the default color is a dark gray
**Before**
**After**
- Do we need to make the border configurable or we generally disable it?
---  
> feat: disable border in visyn header

- src/app/VisynAppContext.tsx
- src/app/VisynAppProvider.tsx
- src/app/header/VisynHeader.stories.tsx
- src/base/clientConfig.ts
- visyn_core/__init__.py
- visyn_core/server/visyn_server.py
- visyn_core/settings/client_config.py
- visyn_core/settings/router.py
- visyn_core/tests/fixtures/app.py
- visyn_core/tests/test_settings.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Removes support for the legacy `/clientConfig.json` and replaces it with a new one based on Pydantic models.
-  
> Migrate clientConfig to Pydantic models

- src/app/VisynAppProvider.tsx
- src/base/clientConfig.ts
- visyn_core/server/visyn_server.py
- visyn_core/settings/client_config.py
- visyn_core/settings/model.py
- visyn_core/tests/test_settings.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Migrates /api/clientConfig to /api/v1/visyn/clientConfig 
-  
> refactor: migrate clientConfig to /api/v1/visyn/clientConfig

- visyn_core/id_mapping/idtype_api.py
Closes #12 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Renamed `id` to `idtype_id` which is the correct string
---
> fix: Error in /api/idtypes endpoint

- src/vis/sidebar/CategoricalColumnSelect.tsx
- src/vis/sidebar/NumericalColumnSelect.tsx
Closes https://github.com/datavisyn/reprovisyn/issues/1107
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Uses order selected as the order in the numerical and categorical multi selects
-  
> feat: allow changing of column order vis

- src/app/header/AboutAppModal.tsx
- src/app/header/ConfigurationMenu.tsx
Coming from https://github.com/datavisyn/reprovisyn/issues/852
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Passed the bottom prop to `AboutAppModal` as currently it is not used
- We need to position something custom at the bottom of the About dialog in Ordino Enterprise
- Changed `was developed` by to `is developed by`
Example: 
-  
> feat: propagate `bottom` prop to `AboutAppModal`

- .github/workflows/build_nightly.yml
Closes https://github.com/datavisyn/github-maintenance/issues/55
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> nightly build of main and develop

- src/app/VisynAppProvider.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Ads the notification and modal providers such that apps don't have to do it (or forget it).
-  
> feat: add notifications and modals providers

- package.json
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Change log of https://github.com/lineupjs/lineupjs/releases/tag/v4.8.0
- 🚀 Features
- https://github.com/lineupjs/lineupjs/pull/614 feat: filter missing values improvements
- https://github.com/lineupjs/lineupjs/pull/612 feat: advanced boolean parsing
- https://github.com/lineupjs/lineupjs/pull/613 feat: allow for custom HTML label generation
- https://github.com/lineupjs/lineupjs/pull/611 feat: add support for 1px min bar
- 🐛 Bugs Fixes
- https://github.com/lineupjs/lineupjs/pull/626 fix: remove tooltip for missing values of BoxPlotColumn
- Change log of https://github.com/lineupjs/lineupjs/releases/tag/v4.9.0
- 🚀 Features
- https://github.com/lineupjs/lineupjs/pull/631 feat: search next with pressing enter
- 🐛 Bugs Fixes
- …
> deps: update to lineupjs@4.9.0

- requirements.txt
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Changes pyjwt to the recommend [crypto] install variant: https://pyjwt.readthedocs.io/en/latest/installation.html#cryptographic-dependencies-optional, as otherwise some apps won't have it installed and can't verify certain signatures. 
-  
> deps: change pyjwt to pyjwt[crypto]

- src/utils/fromNow.ts
Closes https://github.com/datavisyn/reprovisyn/issues/1213
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Set formatter language to English 
-  Alternatively, if we do not to hard code the language, we could allow a `customFormatter` argument to the `fromNow` function
> Set formatter language to English in fromNow util function

- deploy/oauth/README.md
- deploy/oauth/docker-compose.yaml
- deploy/oauth/keycloak/master-realm.json
- deploy/oauth/keycloak/master-users-0.json
- deploy/oauth/oauth2-proxy.cfg
Closes https://github.com/datavisyn/reprovisyn/issues/859
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- add oauth2/keycloak test environment and readme
-  
> docs: Add oauth2/keycloak test environment

- package.json
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The GH Action build of the visyn_core develop branch is currently [failing with some connection error in Cypress](https://github.com/datavisyn/visyn_core/actions/runs/6309631417/job/17171201063).
- The [error seems to be known](https://github.com/cypress-io/cypress/issues/14175#issuecomment-1736638308) and a [possible fix](https://github.com/cypress-io/cypress/issues/14175#issuecomment-1736659169) is an update to the most recent Cypress version 13.2. 
- The build [here](https://github.com/datavisyn/visyn_core/actions/runs/6107883832/job/16575780534) was successful without any further changes. 
Before
After
---
> deps: update to Cypress 13.2

- src/vis/scatter/utils.ts
Closes https://github.com/datavisyn/reprovisyn/issues/290
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds the shape to the tooltip in the scatterplot
-  
> feat: adding shape to scatterplot tooltip

- package.json
- requirements.txt
* deps: pin werkzeug to 2.3.7 by @dvmoritzschoefl in https://github.com/datavisyn/visyn_core/pull/96
**Full Changelog**: https://github.com/datavisyn/visyn_core/compare/v4.1.0...v4.1.1
> Release 4.1.1

- src/vis/bar/hooks/useGetBarScales.ts
Closes bar chart crash issue of #99
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Multiples can be loaded in the bar chart plot (tested in Ordino Enterprise prod build)
-  We might want to change the other implementations of Arquero's `filter` function elsewhere in the code.
> fix: bar chart crash issue in Various bugs vis components #99

- visyn_core/security/store/alb_security_store.py
- visyn_core/security/store/oauth2_security_store.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Logs content of token (not the token itself!) if no email field matched. This makes it significantly easier to figure out which fields to use. 
-  
> refactor: log entire token payload if no email field matched

- package.json
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds `@emotion/react` as that is required by Mantine 6. 
-  
> deps: add @emotion/react

- src/views/visyn/proxy/ProxyViewComponent.tsx
Contributes to https://github.com/datavisyn/reprovisyn/issues/1413
Required for https://github.com/datavisyn/reprovisyn/pull/1414
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- add data-testid to proxy view iframe
-  
> test: add `data-testid` to proxy view iframe

- visyn_core/security/store/oauth2_security_store.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add debug log for access token in oauth security store
-  
> feat: debug log for access_token in oauth security store

- package.json
- src/vis/raincloud/Raincloud.tsx
- src/vis/stories/fetchIrisData.tsx
- src/vis/violin/ViolinVis.tsx
- visyn_core/security/store/oauth2_security_store.py
- visyn_core/settings/model.py
- visyn_core/settings/utils.py
* feat: add get_default_postgres_url utility (https://github.com/datavisyn/visyn_core/pull/136)
* feat: debug log for access_token in oauth security store (https://github.com/datavisyn/visyn_core/pull/139)
* Fix: tooltip bug in violin plot (https://github.com/datavisyn/visyn_core/pull/140)
* Handle null value only columns in raincloud plot (https://github.com/datavisyn/visyn_core/pull/130)
> Release 7.0.1

- src/vis/general/layoutUtils.ts
- src/vis/interfaces.ts
- src/vis/raincloud/Raincloud.tsx
- src/vis/raincloud/RaincloudGrid.tsx
- src/vis/raincloud/utils.ts
- src/vis/scatter/utils.ts
- src/vis/stories/Iris.stories.tsx
see https://github.com/datavisyn/reprovisyn/pull/1466
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Show label of column instead of id in tooltips
-  
> feat: use label column in Vis tooltips

- package.json
- src/vis/general/layoutUtils.ts
- src/vis/interfaces.ts
- src/vis/raincloud/Raincloud.tsx
- src/vis/raincloud/RaincloudGrid.tsx
- src/vis/raincloud/utils.ts
- src/vis/scatter/utils.ts
* feat: use label column in Vis tooltips (https://github.com/datavisyn/visyn_core/pull/141)
> Release 7.0.2

- visyn_core/settings/utils.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds the ability to override the `driver` in get_default_postgres_url
-  
> feat: add driver option to get_default_postgres_url

- visyn_core/security/store/alb_security_store.py
- visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add debug logging to ALB security store
-  
> feat: add debug logging to alb_security_store

- cypress/e2e/health-check.cy.ts
- src/app/header/UserMenu.tsx
Fixes the cypress test as the dom structure changed in mantine7
> fix: cypress tests

- visyn_core/settings/utils.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds support for overriding the port of the `get_default_postgres_url` via `POSTGRES_PORT`
-  
> feat: add POSTGRES_PORT to get_default_postgres_url

- src/demo/MainApp.tsx
- src/vis/scatter/LabelingOptions.tsx
- src/vis/scatter/ScatterVis.tsx
- src/vis/scatter/ScatterVisSidebar.tsx
- src/vis/scatter/interfaces.ts
- src/vis/scatter/utils.ts
Closes #180 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- add labels to scatter plot and provide three modes (Show labels for selected points, show all, hide all)
-  
> feat: scatter plot labeling options

- src/app/header/DatavisynLogo.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> fix: vertical position of datavisyn logo in visyn header

- package.json
- src/app/header/DatavisynLogo.tsx
- src/vis/scatter/ScatterVis.tsx
- src/vis/scatter/utils.ts
* fix: vertical position of datavisyn logo in visyn header by @dvdanielamoitzi in https://github.com/datavisyn/visyn_core/pull/193
* fix(vis): transparent scatterplot labels  by @dv-raghad-jamalaldeen in https://github.com/datavisyn/visyn_core/pull/192
**Full Changelog**: https://github.com/datavisyn/visyn_core/compare/v8.1.0...v8.1.1
> Release 8.1.1

- package.json
- src/app/header/ConfigurationMenu.tsx
- src/app/header/UserMenu.tsx
* fix: fixed bug when textfont has no color (https://github.com/datavisyn/visyn_core/pull/205)
> Release 8.1.3

- visyn_core/server/visyn_server.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds HEAD listener to the health endpoint (as needed by playwright for example)
- The default is only GET, so now we have both
-  
> fix: add HEAD method to health endpoint

- src/vis/bar/barComponents/XAxis.tsx
- src/vis/bar/barComponents/YAxis.tsx
- src/vis/legend/ColorLegend.tsx
- src/vis/legend/ColorLegendVert.tsx
- src/vis/sidebar/VisTypeSelect.tsx
Some font sizes have been set wrongly during mantine7 migration. I have now checked the changes in the mantine7 PR and fixed all wrong font size assignments here.
> Fix: font sizes (mantine)

- src/app/login/UserStoreUIMap.tsx
- src/app/login/VisynLoginMenu.tsx
Closes #212 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Smaller font size for Mantine Anchor (links) 
**Before**
**After**
-  
> fix(ui): font size of mantine anchors (links)

- src/vis/EagerVis.tsx
Closes https://github.com/datavisyn/visyn_core/issues/219
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> fix: stale state in vis when changing vis type

- src/vis/scatter/ScatterVis.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> hotfix: scatterplot labels

- src/app/login/VisynLoginForm.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> refactor: rename data-cy to data-testid

- package.json
- src/app/login/VisynLoginForm.tsx
* refactor: rename data-cy to data-testid by @puehringer in https://github.com/datavisyn/visyn_core/pull/234
**Full Changelog**: https://github.com/datavisyn/visyn_core/compare/v9.1.2...v9.1.3
> Release v9.1.3

- src/vis/scatter/utils.ts
- src/vis/stories/fetchIrisData.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- use `idToLabelMapper` instead of `toString()`
-  
> fix(scatterplot): use label in selection labels

- package.json
- src/vis/sidebar/MultiSelect.tsx
- src/vis/stories/Iris.stories.tsx
- src/vis/stories/Vis/Bar/BarRandom.stories.tsx
- src/vis/stories/Vis/Correlation/CorrelationIris.stories.tsx
- src/vis/stories/Vis/Heatmap/HeatmapRandom.stories.tsx
- src/vis/stories/Vis/Hexbin/HexbinRandom.stories.tsx
- src/vis/stories/Vis/Raincloud/RaincloudRandom.stories.tsx
- src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
- src/vis/stories/Vis/Violin/ViolinIris.stories.tsx
- src/vis/violin/ViolinVis.tsx
- src/vis/violin/utils.ts
Partially fixed: #227
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- fixed selection events in violin plot not working properly
- disabled zoom for violin plot
- fixed:  vis configurations not applied in storybook
-  
> fix(vis): violin vis selection events

- visyn_core/id_mapping/idtype_api.py
- visyn_core/security/jwt_router.py
- visyn_core/server/mainapp.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- replace `xyz.api_route(..., methods=["GET", "POST"])` with explicit method functions `xyz.get(...)` and `xyz.post(...)`
---- 
> refactor: replace `.api_route()` with  explicit method functions

- src/vis/scatter/ScatterVis.tsx
- src/vis/scatter/utils.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- fixed small bug with missing label mapping
- added additional margin for facets title
-  
> Fix scatter vis label mapping

- .github/workflows/build.yml
- .github/workflows/chromatic.yml
- .storybook/main.js
- chromatic.config.json
- package.json
- Updated chromatic version
- Added github workflow to build and deploy the stories
- Deploying all stories whenever something in src/vis or any .stories file changes
CI:
Deployed stories:
-  
> feat: initialize chromatic

- package.json
- src/app/VisynAppProvider.tsx
- src/base/clientConfig.ts
- visyn_core/__init__.py
- visyn_core/sentry/sentry_proxy_router.py
- visyn_core/settings/client_config.py
- visyn_core/settings/model.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Integrates Sentry into the `VisynApp`. The DSN in set in the backend, sent via the client config to the frontend, and used there to initialize the Sentry instance. 
- Caveat: If an error occurs before the VisynAppProvider is initialized, Sentry won't be initialized and thus no errors will be reported. 
To use, simply set to your DSN. This will be shared with the application via client config and used to initialize the Sentry instance.
```
VISYN_CORE__SENTRY__DSN=...
```
-  
> feat: Sentry integration

- .github/workflows/build.yml
- .github/workflows/chromatic.yml
- .storybook/main.js
- chromatic.config.json
- package.json
- requirements.txt
- requirements_dev.txt
- src/app/VisynAppProvider.tsx
- src/base/clientConfig.ts
- src/vis/sidebar/AggregateTypeSelect.tsx
- visyn_core/__init__.py
- visyn_core/sentry/sentry_proxy_router.py
- visyn_core/settings/client_config.py
- visyn_core/settings/model.py
* chore(deps-dev): update black requirement from ~=24.3.0 to ~=24.4.2 (https://github.com/datavisyn/visyn_core/pull/314)
* chore(deps-dev): bump ruff from 0.3.5 to 0.4.7 (https://github.com/datavisyn/visyn_core/pull/322)
* chore(deps): bump python-dateutil from 2.8.2 to 2.9.0.post0 (https://github.com/datavisyn/visyn_core/pull/282)
* chore(deps): bump react-highlight-words from 0.17.0 to 0.20.0 (https://github.com/datavisyn/visyn_core/pull/215)
* feat: initialize chromatic (https://github.com/datavisyn/visyn_core/pull/334)
* fix(vis-heatmap): disable deselection of aggregation type (https://github.com/datavisyn/visyn_core/pull/333)
* feat: Sentry integration (https://github.com/datavisyn/visyn_core/pull/319)
> Release 10.2.0

- src/vis/sidebar/MultiSelect.tsx
- src/vis/sidebar/SingleSelect.tsx
- src/vis/stories/fetchBreastCancerData.tsx
- added the column description to the selected values in single selects, to the options in single selects, to selected values (pills) in multi selects and to the tooltips
- The screenshot below shows a mixture of columns with and without descriptions, covering all possible use-cases
-  
> feat(vis): add column description to selects and pills

- package.json
- src/vis/general/SortIcon.tsx
* Feat: add property isShiftKeyPressed to sortIcon (https://github.com/datavisyn/visyn_core/pull/362)
> Release 11.0.1

- requirements.txt
- visyn_core/server/visyn_server.py
- visyn_core/settings/model.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add Sentry integration for the backend to enable features like distributed tracing: https://docs.sentry.io/platforms/python/integrations/fastapi/
-  
> feat: add sentry FastAPI integration

- package.json
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- We are currently seeing some type errors like the following, which are introduced by arquero 5.4.1: https://github.com/uwdata/arquero/releases/tag/v5.4.1
```
Error: src/vis/bar/hooks/useGetBarScales.ts(90,15): error TS2345: Argument of type 'any[] | TypedArray' is not assignable to parameter of type 'Iterable<string>'.
Type 'Uint8Array' is not assignable to type 'Iterable<string>'.
The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
Type 'IteratorResult<number, any>' is not assignable to type 'IteratorResult<string, any>'.
Type 'IteratorYieldResult<number>' is not assignable to type 'IteratorResult<string, any>'.
Type 'IteratorYieldResult<number>' is not assignable to type 'IteratorYieldResult<string>'.
Type …
```
> feat: pin arquero to 5.4.0 because of typing issues

- package.json
* feat: pin arquero to 5.4.0 because of typing issues (https://github.com/datavisyn/visyn_core/pull/369)
> Release 11.1.1

- package.json
- requirements.txt
- requirements_dev.txt
- src/vis/sidebar/SingleSelect.tsx
- chore(deps-dev): bump ruff from 0.4.8 to 0.4.10 (https://github.com/datavisyn/visyn_core/pull/372)
- chore(deps): bump pydantic from 1.10.16 to 1.10.17 (https://github.com/datavisyn/visyn_core/pull/373)
- chore(deps): update sqlalchemy requirement from <=1.4.49,>=1.4.40 to >=1.4.40,<=1.4.52 (https://github.com/datavisyn/visyn_core/pull/374)
- chore(deps): bump openpyxl from 3.1.3 to 3.1.4 (https://github.com/datavisyn/visyn_core/pull/375)
- fix: use id instead of name for selected items (https://github.com/datavisyn/visyn_core/pull/377)
> Release 11.1.2

- src/vis/scatter/ScatterVis.tsx
- src/vis/scatter/utils.ts
Closes #391 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- selections are now also properly reflected on the histogram of scatter vis matrix
-  
> fix(vis): histogram selection logic for scatter vis

- src/vis/bar/BarChart.tsx
- src/vis/bar/interfaces.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> fix(vis): make bar chart interface properties optional

- src/vis/bar/BarVisSidebar.tsx
- src/vis/hexbin/HexbinVisSidebar.tsx
- src/vis/scatter/ColorSelect.tsx
- src/vis/scatter/ScatterVisSidebar.tsx
- src/vis/sidebar/AggregateTypeSelect.tsx
- src/vis/sidebar/SingleSelect.tsx
- src/vis/violin/ViolinVisSidebar.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- re-enable numerical column scales
-  
> fix(scatter): Re-enable sequential and divergent color scales

- .github/dependabot.yml
for less dependabot spam.
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> dependabot: add grouping for npm mantine and github actions

- src/vis/scatter/utils.ts
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/33
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Use a map for resolved values in facet setting to reduce the number of iterations for generating tooltip labels
- N/A
- N/A
> refactor: improve time complexity for tooltip labels + minor fixes

- src/vis/scatter/ScatterVis.tsx
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/30
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- allow selecting points from multiple facets
-  
> feat(vis-type: scatter): selecting points from multiple facets

- src/app/header/UserMenu.tsx
- src/app/header/VisynHeader.tsx
- src/vis/scatter/utils.ts
Closes #473
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add null check before displaying the user menu
- N/A
- N/A
> fix: add null check for the user

- src/vis/EagerVis.tsx
- src/vis/heatmap/interfaces.ts
- src/vis/interfaces.ts
- src/vis/scatter/Regression.tsx
- src/vis/scatter/utils.ts
- src/vis/violin/utils.ts
Closes https://github.com/datavisyn/bioinsight/issues/510, https://github.com/datavisyn/bioinsight/issues/516
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- fixed a bug in `EagerVis` causing the a wrong configuration in the scatterVis
- sort facets in scattervis and violinvis by domain or alphabetically if not given
-  
> Feature: Facet sorting

- src/vis/bar/BarChart.tsx
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/26
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fix scroll issue in faceting of the bar charts
-  There is a slight flicker when the container resizes. This can be minimized visually by adding a loading overlay when the container is resizing. The loading overlay logic is in the commented code
EDIT: Flicker has been fixed in https://github.com/datavisyn/visyn_core/pull/480/commits/5ce0f8d1c43fa1f6d49a0804fd43569ba395ed5a using @oltionchampari's suggestion
> fix: bar chart facets horizontal scrollbar

- src/demo/MainApp.tsx
- src/vis/bar/BarChart.tsx
- src/vis/bar/BarChartSortButton.tsx
- src/vis/bar/SingleEChartsBarChart.tsx
- src/vis/bar/interfaces.ts
- src/vis/general/constants.ts
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/28
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add sorting to the bar charts implementation in echarts
- All the plots can be sorted at once with the sort icon in the header
- Currently the plots in faceted view cannot be sorted individually
- Plots are arranged in descending order by default (configurable sorting)
- Facets are arranged in ascending order
- N/A
> feat: implement bar plot sorting

- src/vis/vishooks/hooks/usePan.ts
Fixing stale state issue making the panning sluggish.
> Adjust usepan hook

- src/vis/EagerVis.tsx
- src/vis/stories/Iris.stories.tsx
- src/vis/stories/Vis/Bar/BarRandom.stories.tsx
- src/vis/stories/Vis/Correlation/CorrelationIris.stories.tsx
- src/vis/stories/Vis/Heatmap/HeatmapRandom.stories.tsx
- src/vis/stories/Vis/Hexbin/HexbinRandom.stories.tsx
- src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx
- src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx
- src/vis/stories/Vis/Violin/ViolinIris.stories.tsx
- src/vis/vishooks/hooks/useControlledUncontrolled.ts
Closes https://github.com/datavisyn/visyn_core/issues/498
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Tries to fix the Vis by implementing (parts of) https://github.com/datavisyn/visyn_core/issues/498
-  
> feat: simplify useUncontrolled in Vis

- .github/workflows/release.yml
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> feat: Fix release.yaml

- src/vis/bar/BarChart.tsx
- src/vis/bar/SingleBarChart.tsx
- src/vis/bar/barComponents/XAxis.tsx
- src/vis/bar/barTypes/GroupedBars.tsx
- src/vis/bar/barTypes/StackedBars.tsx
- src/vis/bar/hooks/useGetGroupedBarScales.ts
- src/vis/bar/interfaces.ts
- src/vis/bar/utils.ts
- src/vis/interfaces.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- click on xaxis label now selects the whole corresponding bar
- it is now possible to pass the default sort state via the vis config
- legend will accept the passed domain for item order
-  
> feat: barvis improvements

- src/vis/sankey/SankeyVis.tsx
Closes #173 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Handle undefined values, show them as 'Unknown'
-  
> fix(vis-type: sankey): Handle undefined/missing values

- src/vis/index.ts
Closes https://github.com/datavisyn/communication_bi_ordino/issues/89
Coming from https://github.com/datavisyn/reprovisyn/pull/2055
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Added missing box plot export
- N/A
- https://github.com/datavisyn/reprovisyn/pull/2055 depends on this
> fix: export box plot interfaces

- src/vis/scatter/useData.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- add null checks in useData
-  
> fix(vis-type: scatter): add null check in `useData` hook

- src/vis/scatter/useData.tsx
- src/vis/scatter/useDataPreparation.ts
Closes https://github.com/datavisyn/visyn_core/issues/588
Added description to axis titles in SPLOM mode
> Added description to SPLOM axes

- .github/workflows/release.yml
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> feat(ci): Finalize Automated Release Workflow

- src/vis/bar/BarChart.tsx
- src/vis/bar/components/FocusFacetSelector.tsx
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/48
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fix focus facet selector bug
https://github.com/user-attachments/assets/83fe1b07-01e7-4837-a076-71d8709114e7
- N/A
> fix(vis-type: bar): focus facet selector + sort facets alphabetically

- requirements.txt
- requirements_dev.txt
- visyn_core/dbview.py
- visyn_core/plugin/registry.py
- visyn_core/rdkit/img_api.py
- visyn_core/security/manager.py
- visyn_core/tests/fixtures/app.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Updates to latest FastAPI and ruff
- Removes email-validator as it is not used right now and should be a peer dependency (I think no one has used that, so maybe only a minor release?)
- Adds some `make all` fixes
-  
> deps: upgrade to fastapi 0.115.6 and ruff 0.9.1

- src/vis/vishooks/math/matrix4x4.ts
- src/vis/vishooks/math/vector3.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Exports Vector3 and Matrix4x4 to avoid: 
```
The inferred type of '...' cannot be named without a reference to '../../../../node_modules/visyn_core/src/vis/vishooks/math/interfaces'. This is likely not portable. A type annotation is necessary.
```
-  
> feat: export Vector3 and Matrix4x4

- src/vis/bar/BarChart.tsx
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/51
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixed bar chart height calculation when faceted with long charts and many facets
https://github.com/user-attachments/assets/3dde64d5-b8ff-4015-aca3-2ab70bc9c8d9
- N/A
> fix(vis-type: bar): label layouting issue in the bar plot

- src/echarts/useChart.ts
- src/vis/vishooks/hooks/VisHooks.stories.tsx
Added VisualMap component to useChart to enable color mapping
> feat: Added visual map component

- src/utils/colors.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
-  Updated the categoricalColors10: moved yellow back (to align with the decent colors)
-  Added a new color palette: categoricalColors10Muted (see screenshot 2nd row)
- both color scales are aligned in their order now, which makes it easy to use for e.g. selected / deselected items
- updated the decent green colors to better match their strong version
-  
> feat: update categorical colors and export muted versions

- visyn_core/plugin/parser.py
TODO: template was removed on mobile, add back later
> Discovered 1 plugin(s): visyn_core@16.2.1.dev0
> feat: log plugin version in upon server start

- src/vis/general/index.ts
~Closes *list issues numbers here*~
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- [] ~he PR is connected to the corresponding issue (via `Closes #...`)~
- Adds LegendItem to the export of `visyn_core/vis`
The LegendItem is used in Aevidence where the code is currently duplicated.
--
-  
> feat: export vis LegendItem

- src/app/VisynAppProvider.tsx
- visyn_core/__init__.py
- visyn_core/middleware/fastapi_metrics_middleware.py
- visyn_core/plugin/model.py
- visyn_core/security/dependencies.py
- visyn_core/security/manager.py
- visyn_core/sentry/sentry_proxy_router.py
- visyn_core/server/visyn_server.py
- visyn_core/settings/model.py
- visyn_core/tests/fixtures/app.py
- visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Protects all routes by default, requiring authentication
- **Breaking change**: If your app relies on unauthenticated routes (i.e. for codegen or so), use the escape hatch for plugins by overriding `paths_without_authentication` 
- Adds wait for sentry to ensure sentry is loaded
- Adds loading the sentry users on each request
-  
> feat: protect all routes by default and add sentry init

- package.json
- visyn_core/__init__.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Updates to visyn_scripts 13.1.0
- Fixes trailing slash in /api/sentry/ endpoint
-  
> deps: update to visyn_scripts 13.1.0

- visyn_core/server/visyn_server.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Ignore some verbose paths like /api/loggedinas from being sampled
-  
> feat: use traces_sampler to ignore certain paths from being sampled

- visyn_core/sentry/sentry_proxy_router.py
- visyn_core/settings/model.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add some more configuration options to improve usage of self hosted sentry with self signed certificates.
-  
> feat: consume ca_certs for Sentry frontend proxy

- visyn_core/sentry/sentry_proxy_router.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- In case Sentry doesn't send a proxy header, we will simply omit it for now to make FastAPI happy...
-  
> feat: allow optional Sentry proxy headers

- src/demo/index.initialize.tsx
- visyn_core/sentry/sentry_proxy_router.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds a default Sentry configuration as inspiration for easier testing
- And includes a final attempt to make the sentry proxy work in a self hosted and self signed certificate environment with proxying enabled and many other roadblocks...... 
-  
> feat: add Sentry demo configuration

- src/app/VisynAppProvider.tsx
- visyn_core/__init__.py
- visyn_core/celery/app.py
- visyn_core/dev_celery.py
- visyn_core/sentry/sentry_integration.py
- visyn_core/server/visyn_server.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds `main_app` parameter to `create_celery_worker_app` to ensure the right app is used for Celery tasks
- Moves Sentry stuff to own file for readability
-  
> feat: add main_app parameter to celery

- requirements.txt
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds SQLAlchemy2 stubs for better type completion. Just a patch because it doesn't change any features or so.
-  
> deps: add sqlalchemy2-stubs

- src/vis/scatter/useData.tsx
- src/vis/scatter/useDataPreparation.ts
Closes #771 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixed legend toggle in scatter plot
https://github.com/user-attachments/assets/04c7a2f9-66c1-4ed0-9cd7-bca881cb7e27
- N/A
> fix(vis): scatter plot legend toggle for splom

- visyn_core/security/store/oauth2_security_store.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Sometimes in the OAuth2-Proxy, an Authorization header is forwarded which starts with "Bearer ", which we can't decode of course.
-  
> feat: remove Bearer prefix from access token if exists

- src/components/visyn-combobox/stories/combobox.stories.tsx
- src/components/visyn-combobox/stories/single-select.tsx
- src/components/visyn-combobox/styles.ts
- src/components/visyn-combobox/visyn-option.tsx
- src/components/visyn-combobox/visyn-options-dropdown.tsx
- src/components/visyn-combobox/visyn-select-target.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
> Feat: add unified VisynSelect

- deploy/oauth/docker-compose.yaml
Closes N/A
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Update keycloak docker compose
- Not sure if we still need the changes in `etc/hosts`
> fix: update docker compose to start  keycloak locally

- package.json
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Update to [lineup@4.13.0](https://github.com/lineupjs/lineupjs/releases/tag/v4.13.0)
- https://github.com/lineupjs/lineupjs/pull/684 feat: deselect as default action for selection checkbox
-  
> deps: lineupjs@4.13.0

- package.json
- deps: lineupjs@4.14.0 -> see https://github.com/lineupjs/lineupjs/releases/tag/v4.14.0
> deps: lineupjs@4.14.0

- deploy/oauth/docker-compose.yaml
- src/hooks/useEvent.tsx
useEvent has too strict typing. I think the problem here is unknown which sometimes leads to a return value of (...) => any as type.
Changing it to any and specifying the return type directly solved the issue for me
> fix(visyn_core/hooks): useEvent typing

- package.json
- deps: lineupjs@4.14.1 -> https://github.com/lineupjs/lineupjs/releases/tag/v4.14.1
-  
> deps: lineupjs@4.14.1

- package.json
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- lineupjs@4.15.0
- feat: Add intuitive multi-term search support with advanced filter options for string columns and search dialog https://github.com/lineupjs/lineupjs/pull/696
-  
> deps: lineupjs@4.15.0
