datavisyn/visyn_core

src/base/clientConfig.ts, visyn_core/__init__.py, visyn_core/settings/model.py, visyn_core/settings/router.py, visyn_core/tests/test_settings.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds a `/api/clientConfig` route to more easily configure the clientConfig, as previously it was required to be mounted as static file `/clientConfig.json`. Now, if `/api/clientConfig` is not null, it will this instead. 
-  
=> Add api/clientConfig to more easily configure the clientConfig

src/vis/Vis.tsx, src/vis/scatter/ScatterVis.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Very small change to allow for the hiding of the dragmode options for scatterplots
-  
=> Hide dragmode UI option

src/app/VisynAppProvider.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Avoid unmounting the app if the client config reloads due to a change of the user
-  
=> fix: avoid unmount if client config is reloaded

visyn_core/server/visyn_server.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Changes the order of initialization calls to ensure the `init_app` is called after everything else is loaded. 
-  
=> Change order of init_app to ensure every visyn feature is initialized

visyn_core/server/visyn_server.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add `RequestContextPlugin` very last to ensure it is the last middleware (i.e. after init_app). 
-  
=> fix: add context middleware last to ensure it is loaded after init_app

requirements_dev.txt
As pyright fails with the following error with version 1.1.309, we now pinned it to version 1.1.308
```
pyright visyn_core setup.py
/home/daniela/Workspaces/standalone_repos/visyn_core/visyn_core/xlsx.py
/home/daniela/Workspaces/standalone_repos/visyn_core/visyn_core/xlsx.py:62:67 - error: "object*" is not iterable
"__iter__" method not defined (reportGeneralTypeIssues)
/home/daniela/Workspaces/standalone_repos/visyn_core/visyn_core/xlsx.py:51:13 - error: "object*" is not iterable
"__iter__" method not defined (reportGeneralTypeIssues)
/home/daniela/Workspaces/standalone_repos/visyn_core/visyn_core/id_mapping/manager.py
/home/daniela/Workspaces/standalone_repos/visyn_core/visyn_core/id_mapping/manager.py:98:17 - error: "object*" is not iterable
"__iter__" method not defined …
```
=> Fix: Pin pyright to version 1.1.308

visyn_core/server/visyn_server.py, visyn_core/settings/model.py, visyn_core/tests/test_settings.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Set the log level via `VISYN_CORE__LOG_LEVEL` to `DEBUG`, `INFO`, etc. if you only want to override the logging level.
- Otherwise you must override the whole logging config of the root logger in `visyn_core.logging.root.level`
----
=> feat: add `log_level` config value to settings

visyn_core/security/model.py, visyn_core/security/store/alb_security_store.py, visyn_core/security/store/oauth2_security_store.py, visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Some of our stores are just parsing the access token from an IdP and get the user from that. Here, we now add the ability to store the underlying oauth2 access token and use it for downstream tasks like requests to other services. This is for example required for apps using the on-behalf of flow to access other apps.
-  
=> feat: add oauth2_access_token to User model

src/app/login/VisynLoginMenu.tsx, visyn_core/security/store/alb_security_store.py, visyn_core/security/store/oauth2_security_store.py, visyn_core/settings/model.py, visyn_core/tests/test_security_login.py, visyn_core/tests/test_settings.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Sometimes, tokens look different across users, so defining an ordered array of fields to look in allows supporting multiple token layouts.
- Changed the way how env variables are loaded by default: now, all string values will be parsed as json (if possible). To avoid this, simply name the env variable (not the setting!) `..._as_string`. This will disable the json parsing.
-  
=> feat: added ability to define multiple email fields in alb and oauth2 stores

package.json
Reverts datavisyn/visyn_core#103, because the breaking change in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67132 is reverted as well.
=> Revert "deps: pin @types/react to 18.2.31"

src/vis/bar/BarChart.tsx, src/vis/correlation/CorrelationMatrix.tsx, src/vis/sidebar/VisTypeSelect.tsx, src/vis/stories/Vis/Bar/BarRandom.stories.tsx, src/vis/stories/Vis/Correlation/CorrelationIris.stories.tsx, src/vis/stories/Vis/Heatmap/HeatmapRandom.stories.tsx, src/vis/stories/Vis/Hexbin/HexbinRandom.stories.tsx, src/vis/stories/Vis/Raincloud/RaincloudRandom.stories.tsx, src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx, src/vis/stories/Vis/Scatter/ScatterRandom.stories.tsx, src/vis/stories/Vis/Violin/ViolinIris.stories.tsx
- fixed storybook build for `vis`
- centered loader for bar chart
- show description in correlation matrix column labels (covers bioinsight use case)
=> fix: fix storybook by wrapping all Vis in VisProvider

visyn_core/xlsx.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- escape `+`,`-`,`@`,`=` in `_json2xlsx` in order to prevent csv injection. Previously, passing formulas or DDE scripts were executed after download. A malicious user might use upload a CSV file with formulas, and other users downloading it as xlsx will then have formulas/macros evaluated (after clicking yes to many warnings...) 
-  
=> feature: prevent csv injection in xlsx export

src/ranking/overrides/DatavisynTaggle.tsx, src/ranking/score/interfaces.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Allows directly passing a desc instead of a builder for scores. This is useful if you already have a predefined desc that you want to use.
-  
=> Extended ISingleScoreResult to except column desc directly

src/vis/correlation/CorrelationVis.tsx, src/vis/raincloud/RaincloudGrid.tsx
Closes Language strings of #99
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixed the error messages in Correlation and Raincloud plot
-  N/A
=> fix: language strings

src/vis/EagerVis.tsx, src/vis/VisSidebar.tsx, src/vis/bar/BarVisSidebar.tsx, src/vis/scatter/ScatterVisSidebar.tsx, src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx, src/vis/violin/ViolinVisSidebar.tsx
Closes #114 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The filter buttons are not visible anymore for the components which do not have a filter callback
-  N/A
=> fix: hide filter if no callback is provided

src/vis/EagerVis.tsx
We have the requirement to hide the heatmap in the general purpose vis. This PR introduces a property "visTypes" for the <Vis /> component which enables the developer to specify which vis types to show as options in the sidebar. If not specified, all vis types will be used.
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- added visTypes prop to Vis component
- filtering by visTypes when registering the vis types
In this example I have only passed `visTypes={[ESupportedPlotlyVis.HEATMAP]}` to the Vis component, and as you can see there are no more options in the sidebar:
-  I'm not entirely sure if this is the way we want to do it, there would be the possibility to exclude certain vis types which might be better as newly introduced vis types would then show up by default whereas in my current …
=> Add possibility to specify which vis types to show in the sidebar

visyn_core/settings/model.py, visyn_core/settings/utils.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds a `get_default_postgres_url` utility to be used when defining default urls for postgres. The hostname for postgres may differ locally from the one in CI, such that this utility uses a default from an env variable, and falls back to localhost if it is not set. All our CI is configured to set this variable to the correct postgres host. 
-  
=> feat: add get_default_postgres_url utility

src/vis/stories/fetchIrisData.tsx, src/vis/violin/ViolinVis.tsx
Closes #135 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Removing all null values of the plots in the traces (affected props: x, y, ids, transform). In the below screencast, the upper plot contains lots of null values, and as you can see the tooltips are showing up again.
[Screencast from 2024-01-09 19:21:23.webm](https://github.com/datavisyn/visyn_core/assets/57343176/25bb31bc-4a02-4725-8833-09072cc71ba4)
-  
=> Fix: tooltip bug in violin plot

src/vis/raincloud/Raincloud.tsx
Closes #99 
- raincloud vis fix: 
- show error overlay for columns with null values only (covers special edge case found in bioinsight)
=> Handle null value only columns in raincloud plot

package.json, requirements.txt, src/vis/EagerVis.tsx, src/vis/heatmap/HeatmapGrid.tsx, src/vis/heatmap/HeatmapText.tsx, visyn_core/settings/utils.py
* fix: cypress tests (https://github.com/datavisyn/visyn_core/pull/159)
* fix: vis is rendered with an invalid config (https://github.com/datavisyn/visyn_core/pull/172)
* feat: add POSTGRES_PORT to get_default_postgres_url (https://github.com/datavisyn/visyn_core/pull/181)
* chore(deps): bump cachetools from 5.3.1 to 5.3.2 (https://github.com/datavisyn/visyn_core/pull/147)
=> Release 8.0.1

src/app/header/ConfigurationMenu.tsx, src/app/header/UserMenu.tsx
Fixes failing cypress tests after https://github.com/datavisyn/reprovisyn/pull/1555
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Added missing `data-testid` attributes
- N/A
- N/A
=> fix: more specific `data-testid` in VisynApp header for Cypress tests

cypress/e2e/health-check.cy.ts, package.json, src/app/header/ConfigurationMenu.tsx, src/app/header/UserMenu.tsx
* fix: more specific `data-testid` in VisynApp header for Cypress tests by @dv-usama-ansari in https://github.com/datavisyn/visyn_core/pull/195
**Full Changelog**: https://github.com/datavisyn/visyn_core/compare/v8.1.1...v8.1.2
=> Release 8.1.2

cypress/e2e/health-check.cy.ts
I'm changing the cypress test to check the app shell to include the text instead of the whole body, as the body get's quite long with the styles. I think this is why it failed [here](https://github.com/datavisyn/visyn_core/actions/runs/8660082947/job/23752989727)
The build withe the cypress tests is successful for this branch: https://github.com/datavisyn/visyn_core/actions/runs/8662349056
-  
=> test: use app shell instead of body in cypress test

src/ranking/overrides/DatavisynTaggle.tsx
- added optional `insertAfter` parameter to `createScoreColumn` in order to better allow positioning of newly added score columns
-  
=> feat: add possibility to insert score column after given column in ranking

src/vis/sidebar/FilterButtons.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Rename the filter labels to make it easier to use
- The option values remain the same
**Before**
**After**
**Tooltips**
* **Keep**: Keep selected points, remove other points
* **Remove**: Remove selected points, keep other points
* **Clear**: Clear all point filters
The filter buttons are disabled in the visyn_core demo app by default. I enabled this for the screenshots above.
---  
=> refactor: rename labels of filter buttons

src/vis/scatter/Regression.tsx, src/vis/scatter/ScatterVis.tsx, src/vis/scatter/utils.ts
Closes #303 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Various scattervis improvements
- show actual x/y axis labels in hovertext instead of only _x_ _y_  
- fix occasional application crash on regression line change
- improve scattervis trace calculation on color/shape column select
-  
=> fix(vis): XY Labels in scatter vis hovertext

src/vis/sidebar/AggregateTypeSelect.tsx
Closes https://github.com/datavisyn/visyn_core/issues/332
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The select is used in the Bar and heat map plots, in both cases same behavior applies. You should not be able to deselect it
-  
=> fix(vis-heatmap): disable deselection of aggregation type

src/app/VisynAppProvider.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds sentry logging to all console.error calls
-  
=> feat: add console integration for Sentry

src/vis/general/SortIcon.tsx
- For the priority sort in Oncoprint, we need to check if the shift key was pressed during the click on the sort icon
- added isShiftKeyPressed property to the callback function in the SortIcon
-  
=> Feat: add property isShiftKeyPressed to sortIcon

src/vis/general/SortIcon.tsx
- Using CTRL instead of SHIFT for the event in the sort icon, to align it with lineup.
-  
=> Fix: use ctrl for priority sort instead of shift

package.json
Closes https://github.com/datavisyn/visyn_core/issues/366
With version 2.12.0 the lasso selection still works. From 2.13.0 upwards the lasso fails.
=> fix: Setting Plotly version to ~2.12.0

package.json, requirements.txt, src/vis/general/SortIcon.tsx, visyn_core/server/visyn_server.py, visyn_core/settings/model.py
* fix: Setting Plotly version to ~2.12.0 (https://github.com/datavisyn/visyn_core/pull/367)
* Fix: use ctrl for priority sort instead of shift (https://github.com/datavisyn/visyn_core/pull/365)
* feat: add sentry FastAPI integration (https://github.com/datavisyn/visyn_core/pull/364)
* chore(deps): bump pydantic from 1.10.14 to 1.10.16 (https://github.com/datavisyn/visyn_core/pull/357)
=> Release 11.1.0

src/vis/vishooks/components/Brush.tsx
Due to a mistake, the `extent` variable was not named to the correct one leading to a null error
=> Fixed refactor issue with extent

src/hooks/Hooks.stories.tsx, src/hooks/index.ts, src/hooks/useSetRef.ts
The problem:
Suppose we have an element which we track with useRef
```
const ref = React.useRef<HTMLElement>();
<div ref={ref} />
```
The ref will not trigger useEffects since the reference never changes, this can cause stale state as seen in pharmDB with the wheel listeners.
The solution:
use a ref callback, which will trigger everytime the component remounts. I encapsulated this logic into a reusable form
For reference, see:
https://legacy.reactjs.org/docs/hooks-faq.html?source=post_page-----eb7c15198780--------------------------------#how-can-i-measure-a-dom-node
https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780
=> Added setRef hook

src/vis/bar/BarChart.tsx, src/vis/bar/BarVis.tsx, src/vis/bar/README.md, src/vis/bar/SingleBarChart.tsx, src/vis/bar/barComponents/FocusFacetSelector.tsx, src/vis/bar/interfaces.ts
Closes #419 
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Add focus facet component to toolbar
- Select focus facet on click on the title and return to overview if clicked again
- Cycling infinitely through all facets in focus mode
[bar-chart-focus-facet.webm](https://github.com/user-attachments/assets/e05e39c7-605a-41fd-bc69-bea6d3d47d0d)
The flag `showFocusFacetSelector` in the bar config is disabled by default and needs to be enabled on demand. We can decide whether or not to show it by default.
----
=> feat(vis): focus facet selector for bar chart

src/vis/scatter/utils.ts
Closes #446
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixed tooltip label for facets in scatter plot
- In single scatter plot
---
- In faceted scatter plot
-  
=> fix(vis-type: scatter): tooltip labels for facets in scatter plot

src/security/LoginUtils.ts, visyn_core/security/jwt_router.py, visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Currently we are returning a 200 with "'not_yet_logged_in'", which is quite confusing (also for tools like Sentry, as it triggers errors afterwards but the request is fine). Let's change it to actually trigger a 401 instead.
- Should be a patch because before it rejected a promise in this case, and now we just return the AjaxError instead.
-  
=> feat: return 401 if not logged in for loggedinas

package.json, src/demo/MainApp.tsx, src/vis/bar/BarChart.tsx, src/vis/stories/explodedData.ts, tsconfig.json
**DRAFT PR**
Closes (https://github.com/datavisyn/visyn_core/issues/516)
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- 
-  
=> fix: ECharts performance

package.json, playwright.config.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The Carousel component is used in ordino and as discussed the mantine packages should all be on core
for easies depdendency management
- Add properly typed playwright-chromatic configuration: https://www.chromatic.com/docs/playwright/configure/
- Add delay for more consistent screenshots
-  
=> fix: add mantine carousel package to dependencies

src/vis/bar/SingleEChartsBarChart.tsx, src/vis/vishooks/hooks/index.ts, src/vis/vishooks/hooks/useChart.ts
By altering the way we import echarts, the bundle size could be reduced from ~9.8 to ~8.5mb. It is loaded when the vis loads. Lazy loading like in plotly is not possible with hooks. If the bundle size is still an issue we need to create a wrapper component like the LazyVis.
https://apache.github.io/echarts-handbook/en/basics/import/
=> perf: Adjusted imports for echarts

src/vis/general/InvalidCols.tsx, src/vis/scatter/ScatterVis.tsx
The problem:
- plotly uses window resize events which is not enough when having react mosaic for instance
The solution:
- use a resize listener and set width/height fixed
=> feat: Used dimensions from parent to resize plotly

src/utils/colors.ts
- Removing gray from the categorical color palette, as gray is our netural color which should be used for unknown categories only, or for visualizations without any categories.
-  
=> Style: remove gray from categorical color palette

src/utils/colors.ts
- new palette with 10 categorical colors
- new palette with 20 categorical colors (based on the 10 categorical colors above)
- the old categorial colors is deprecated
10 colors:
20 colors:
-  
=> Style: Add new palettes for categorical colors

playwright/hexbin/01_general.spec.ts, src/vis/hexbin/HexbinVis.tsx, src/vis/useCaptureVisScreenshot.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The whole `useCaptureVisScreenshot` feels very hacky and should in my opinion be refactored. Currently, the function just "tries" several ways of downloading things, but it can't be sure that it works. 
- What would be better is to have some simple utilities like `downloadPlotly`, `downloadCanvas`, `downloadSVG` which must be passed to the download button (which is rendered in every single vis type anyways). With that, one would be able to simply pass the right function which should be used to download the specific vis type. So if we change a vis type, we also know to adapt the download function. Currently, it is bound to break and there is no way of extending the download functionality. 
- I.e. in this PR, I added the `Boxplot` to be downloaded …
=> fix: show error message if Vis download fails

src/vis/vishooks/hooks/useChart.ts
- cherry picked from commit 7818e9975369078df95158af091e15ef273f6083 that is part of https://github.com/datavisyn/visyn_core/pull/575
[bar-chart-throttle-resize-observer.webm](https://github.com/user-attachments/assets/3ee3dfef-1db8-4d79-b07d-1a817b31ef4c)
I cherry picked the commit because it has by itself already a huge perceived performance impact. Using workers for aggregations and the remaining fixes will be merged with https://github.com/datavisyn/visyn_core/pull/575 and released afterwards.
---  
=> fix(vis-type: bar): jump to full width after rendering narrow initially using debounced resize observer

playwright/boxPlot/04_subcategory.spec.ts, src/vis/scatter/ScatterVis.tsx, src/vis/violin/utils.ts
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Replace the deprecated `categoricalColors` with `categoricalColors10` in scatter plot and violin plot
-  
=> fix: replace `categoricalColors` with `categoricalColors10`

src/vis/bar/SingleEChartsBarChart.tsx, src/vis/bar/interfaces/constants.ts, src/vis/bar/interfaces/enums.ts, src/vis/bar/interfaces/helpers.ts, src/vis/bar/interfaces/interfaces.ts, src/vis/bar/interfaces/internal/constants/group.ts, src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.test.ts, src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.ts
@dv-usama-ansari fixing a grouping issue for the barchart
Found in https://github.com/datavisyn/bioinsight/pull/564#issuecomment-2434939057
- added documentation for various interfaces and enums in https://github.com/datavisyn/visyn_core/commit/2062e112cd3abb58be48b22e90a1fd94ad2fa946
- fixed infinity values caused by grouping with zero values
-  
=> fix(vis-type: bar): grouping with zero values

src/vis/bar/SingleEChartsBarChart.tsx
Closes #600
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixed retaining selection when sort order is changed.
[sort-selection-retain.webm](https://github.com/user-attachments/assets/74052826-7259-41eb-abb1-f8b6458a1d5e)
- It is necessary to use [fine grained pre-conditions](https://github.com/datavisyn/visyn_core/blob/58a3b595ba48d9296158adae2377b43ee3067a2a/src/vis/bar/SingleEChartsBarChart.tsx#L423) for the chart event listeners to dodge issues like these.
=> fix(vis-type: bar): selection is lost when bar plot is sorted

src/vis/bar/SingleEChartsBarChart.tsx
Closes https://github.com/datavisyn/visyn_core/issues/596#issuecomment-2444085682
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Fixed handling of null values for sort state
- N/A
=> fix(vis-type: bar): axis labels when sort state is null

src/vis/correlation/CorrelationMatrix.tsx, src/vis/hexbin/HexbinVis.tsx, src/vis/scatter/ScatterVis.tsx, src/vis/useCaptureVisScreenshot.ts
Closes https://github.com/datavisyn/reprovisyn/issues/2125
**Issue**
**UI/UX/Vis**
**Code**
**PR**
we were passing the id to both the parent and the plotly component + we were not using the `uniquePlotId `prop
Was disabled, although the `useCaptureScreenshot` hook supports svgs
`useCaptureScreenshot` hook was expecting this to be rendered in a canvas which is not the case 
Added the `plotId` to only download the plot and the legend and not the download plot button itself
... the rest of the plots worked already
-  
=> fix: capturing a screenshot is broken for several visualizations

src/vis/vishooks/hooks/usePan.ts
- Added onClick event to usePan
- Returned drag state from usePan
=> feat: Add `onClick` to `usePan`

src/vis/general/index.ts, src/vis/general/layoutUtils.ts
- adding the export of layoutUtils and constants again
-  
=> fix: exports in general vis

package.json
Closes https://github.com/datavisyn/visyn_scripts/issues/104
For completeness the message of Slack explaining the issue:
>  I may have found the problem. storybook 7.6.20 has swc/core 1.9.0 as a dependency. since its the higher version it will be the top level node_modules version alongside with the jest version from visyn_scripts. swc/core for visyn_scripts is hoisted inside visyn_scripts node_modules. if storybook gets updated to 8 it does not have this dependency anymore and the tests will run again since no hoisting happens anymore (swc/core + swc/jest are only dependencies of visyn_scripts else!)
> This explains why resolutions work, but I believe then storybook would break.
> Also I do not know why this is a problem at all, but looking at the visyn_scripts command there are a lot of …
=> Pinned @swc/core to 1.7.42

src/utils/GenomeNavigation.ts, src/utils/index.ts
Probably of interest for more projects.
Utility class that can convert different genome positions (similar to computeChromSizes in gosling.js).
Data is taken from gosling.js for hg38 to remove the dependency for our core.
Use cases would be:
- Drawing genome axis
- Working with tile fetchers in gosling
- Fetching transcripts from our backend
- ...
=> feat: add `GenomeNavigation` class to util package

src/vis/scatter/useLayout.tsx, src/vis/stories/Vis/Scatter/ScatterIris.stories.tsx, src/vis/stories/fetchIrisData.tsx
When a single subplot was supplied to the general vis, the following problem occured:
- A layout spec similar to the one for a single scatterplot was returned for this case, which resulted in the xaxis/yaxis keys being stale
- Got fixed by not having this special case and instead handling everything the same way for subplots and conditionally set parameters like standoff/text truncation/grid instead
=> Refactored single subplot log scaling

src/vis/bar/BarChart.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- With the latest release of @types/react, the `VariableSizeList` is not a "component" anymore
```
src/vis/bar/BarChart.tsx:420:18 - error TS2786: 'VariableSizeList' cannot be used as a JSX component.
Its type 'typeof VariableSizeList' is not a valid JSX element type.
Types of construct signatures are incompatible.
Type 'new <T = any>(props: VariableSizeListProps<T>) => VariableSizeList<T>' is not assignable to type 'new (props: any, deprecatedLegacyContext?: any) => Component<any, any, any>'.
Property 'refs' is missing in type 'VariableSizeList<any>' but required in type 'Component<any, any, any>'.
420                 <VariableSizeList
~~~~~~~~~~~~~~~~
node_modules/@types/react/index.d.ts:1033:9
1033         refs: {
~~~~
'refs' is declared here. …
```
=> fix: VariableSizeList typing

src/scss/vendors/_lineup.scss
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The lineupengine 2.5.3 release changed the way scss is loaded (i.e. `@import` -> `@use`), which breaks the override for the asset location.
- To now reassign the variables, we have to `@use` it before: https://sass-lang.com/documentation/at-rules/use/#reassigning-variables
-  
=> fix: `@use` lineupengine vars to allow overriding them

src/vis/scatter/ScatterVis.tsx, src/vis/scatter/ScatterVisSidebar.tsx, src/vis/scatter/interfaces.ts, src/vis/scatter/useData.tsx, src/vis/scatter/useLayout.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- added back the showLabelLimit option to the scatter plot
-  
=> fix: add back `showLabelLimit` option to scatter visualization

src/vis/vishooks/hooks/useWheel.ts, src/vis/vishooks/hooks/useZoom.ts, src/vis/vishooks/interfaces.ts, src/vis/vishooks/normalizeWheelEvent.ts
Necessary for https://github.com/datavisyn/aevidence_pfizer_sync/issues/149
When having a visualization inside a canvas element that is scrollable, we want to have normal pan/zoom interactions when no modifiers are pressed and default browser behavior for the scrollbar when they are pressed.
This is possible by adding preventDefault for conditionally enabling/disabling browser behavior and skip for conditionally skipping the zoom calculation
=> feat: Add skip/preventDefault conditions to useWheel

package.json, src/vis/vishooks/hooks/useTransformScale.ts
Small explanation why this change is necessary:
In D3 the transform components are translation and scale, resulting in an affine linear transformation that can be applied to scales. For linear scales (that are not piecewise) the default is to transform the domain, since this has some benefits like knowing what the min/max of the currently visible part is. This however has the requirement that the scale is invertible from the range to the domain because to get an updated domain we first need to revert the range and then reapply the new domain to it. For piecewise scales, as well as ordinal scales, this is not possible because there is no 1:1 inversion, resulting in the jiggling behavior we observed.
The solution is to apply the transform to the range instead and letting the domain fixed. …
=> feat: useTransformScale now supports ranged based transforms

requirements.txt
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Use same version range as [Celery](https://github.com/celery/celery/blob/main/requirements/extras/redis.txt)
- Allowing versions from redis >4.5 allows us to install visyn_core alongside Apache Superset
-  
=> deps(pip): ease redis version range

package.json, src/vis/scatter/ScatterVis.tsx, src/vis/scatter/useData.tsx, src/vis/scatter/useDataPreparation.ts, src/vis/scatter/useLayout.tsx
Closes https://github.com/datavisyn/reprovisyn/issues/2249
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Implement click event on the legend to toggle the points in the scatter plot
EDIT: As of https://github.com/datavisyn/visyn_core/pull/690/commits/47071b9b73ca6f750b865be569b923a564617300
https://github.com/user-attachments/assets/066cd8da-fade-4fb0-9d8a-ccfc7e3ecda2
- @thinkh: What should be the behavior of the regression line when we filter out something using the legend items
=> feat: make scatter plot legends clickable

package.json, src/hooks/useAsync.tsx
- Removed **use-deep-compare-effect** from package.json, since we have our own version
- Removed Awaited<T> type, since TS 4.5 has an inbuilt one
- Moved 4 individual state properties to one common object, to remove flaky behavior (double renders with out-of-sync values) in case React will not batch the setStates
=> fix: removed use-deep-compare-effect, removed Awaited type

src/app/VisynAppProvider.tsx, src/demo/index.initialize.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds waitForClientConfig option for VisynAppProvider. Set this to false to skip the wait for the client config. This is useful if the app works even without the client config.
- Default remains true to wait for the clientConfig, so you can gradually migrate apps to load the app while the clientConfig is not initialized.
-  
=> feat: add waitForClientConfig flag to allow skipping the wait for the clientConfig

src/app/header/VisynHeader.stories.tsx, src/security/constants.ts, src/security/interfaces.ts, visyn_core/security/manager.py, visyn_core/security/model.py, visyn_core/security/store/alb_security_store.py, visyn_core/security/store/no_security_store.py, visyn_core/security/store/oauth2_security_store.py, visyn_core/settings/model.py, visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Adds `properties_fields` to the ALB and OAuth2 security stores to enable picking properties from the JWT payload.
- Use case: imagine if there is a field "important_property" in the JWT payload. Currently, there is no way to retrieve this property. Now, just add  "important_property" to your security store settings under `properties_fields` and you have it. 
-  
=> feat: add arbitrary properties to user object, i.e. mapped from the JWT payload

src/vis/general/FastTextMeasure.ts
- Replaced `textEllipsis` function with newer version `fastTextEllipsis` that returns the truncated label and the truncated width instead of only the label.
- Marked other version as deprecated
=> feat: Added fastTextEllipsis function

visyn_core/sentry/sentry_proxy_router.py, visyn_core/settings/model.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- The default timeout of 10s is apparently too little for Sentry, so we bump it to 30s
- We also only return a few select headers to avoid NGINX issues
-  
=> feat: increate Sentry proxy timeout and only return select headers

src/app/VisynAppContext.tsx, src/app/VisynAppProvider.tsx, src/app/VisynEvents.ts, src/app/header/AboutAppModal.tsx, src/app/header/VisynHeader.stories.tsx, src/app/index.ts, src/base/AppContext.ts, src/base/VisynEnv.ts, src/base/event.ts, src/base/index.ts, src/demo/MainApp.tsx, src/demo/index.initialize.tsx, src/hooks/index.ts, src/hooks/useVisynEventCallback.tsx, src/hooks/useVisynEventValue.tsx, src/hooks/useVisynUser.ts, src/security/UserSession.ts, src/security/watcher.ts, visyn_core/plugin/parser.py, visyn_core/server/visyn_server.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Why? I was looking for a way to let apps react to the `Sentry.init` event (both in React but also globally). We previously had the `globalEventHandler` mechanism, but that is completely untyped and uses a custom event system (inspired by jQuery). The modern way to do this is via `window.dispatchEvent`, and the `VisynEvent` is just a typed wrapper around it. 
- Migrates the `useVisynUser`, `watcher`, ... to the new mechanism, while keeping the old `fire` in place to ensure backwards compatibility. Removes usage of session storage to store user, as that is not recommended and has been replaced in favor of a "memory" store, i.e. a variable
- Exposes hooks `useVisynEventCallback` and `useVisynEventValue` to listen to the changes/values of the events. …
=> feat: add VisynEvents to send global events, incl. better Sentry integration

src/base/clientConfig.ts, visyn_core/dbmigration/manager.py, visyn_core/server/visyn_server.py, visyn_core/settings/client_config.py, visyn_core/settings/model.py, visyn_core/tests/fixtures/app.py, visyn_core/tests/test_settings.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Many apps are now using the `init_app` instead of `register` to add their routes, which is currently executed after the custom commands. This means any migrations or so are not available, as they haven't been executed yet.
- Minor change: this is a dev-only feature for listing and executing migrations, so changing it to the new way won't break anything (but actually fix things!)
But how do I actually use custom commands? Simple: 
```
python -m <app>.dev_app db-migration exec <migration-id> upgrade head
```
-  
=> feat: parse commands after init_app such that everything is loaded

src/vis/scatter/ScatterVis.tsx, src/vis/scatter/useData.tsx, src/vis/scatter/useDataPreparation.ts
Closes N/A
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Added legend click behavior for controlled subplots
https://github.com/user-attachments/assets/4832e9ff-8fe0-4d02-a1ed-d3022d93e6cd
- Shall I add the legend click to faceted and scatter plot matrix as well?
- This implementation might not be as straight forward
=> fix: add legend toggle on click for controlled subplots

src/vis/bar/SingleEChartsBarChart.tsx
Closes https://github.com/datavisyn/ordino/issues/2440
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- for facets with no value, the computed height is about `50` wheras the default component rendered has height 300 which is not included into the total height of the variable list. This causes the `no data for facet` message to overlap into the next bar. 
- I removed the min value, another solution is to modify the computed height for empty facets to be min `300`, i do not see this solution causing any side effects though.
-  
=> fix: height of facets with no data in bar chart

src/app/login/UserStoreUIMap.tsx, visyn_core/celery/app.py, visyn_core/dev_celery.py, visyn_core/sentry/sentry_integration.py, visyn_core/server/visyn_server.py, visyn_core/settings/client_config.py, visyn_core/settings/model.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Hotfix for sending username in the Python Sentry instrumentation. For some reason, the asyncio integration breaks it when using the current/isolation scope. 
-  
=> fix: remove AsyncioIntegration as it breaks the SentryUserMiddleware

src/echarts/useChart.ts
Adds `type: 'custom'` support to echarts which is very handy for creating things like lollipop plots for instance
=> feat: Added CustomChart to echarts hook

src/app/VisynAppProvider.tsx, src/components/BlurredOverlay.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Split the `VisynAppProvider` into `VisynAppMantineProvider` and `VisynAppContextProvider` for more flexibility in apps. I.e. sometimes you need the client config to initialize Redux, but when Mantine needs Redux (via modals for example) there is no way to do it in the old architecture. Now it's easy, just render the `VIsynAppContextProvider`, within you create the Redux stuff, and then render the `VisynAppMantineProvider`. 
- Non-breaking change as it just composes things differently, and is also opt-in.
-  
=> feat: split providers for more flexibility in apps

package.json, src/plotly/index.tsx
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Our plotly types are breaking because `@types/plotly.js-dist-min` is referencing `@types/plotly.js` without any constraint: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/plotly.js-dist-min/package.json#L9, causing the latest (thus v3) to be installed. 
- Also inlined the `@types/react-plotly.js` types as they have the same issue...
-  
=> fix: use @types/plotly.js for plotly.js-dist-min

package.json, visyn_core/rdkit/img_api.py
Related to https://github.com/datavisyn/aevidence_pfizer_sync/pull/311
**Issue**
**UI/UX/Vis**
**Code**
**PR**
Sends RDKit's C++ logs to python logger.  
**Reason 1**: RDKit may, for example, log warnings when processing molecules, e.g.,
> [18:09:14] Warning: conflicting stereochemistry - bond wedging contradiction - at atom 26 ignored
The warning is 1) not returned via the API, and 2) does not include what was processed; making it hard/impossible to tell to which data it corresponds.
**Reason 2:** Consistent logging with the rest of the app.
Implemented as discussed in the RDKit Blog: https://greglandrum.github.io/rdkit-blog/posts/2024-02-23-custom-transformations-and-logging.html#connecting-the-rdkit-logs-to-the-python-logger
Not sure if this is the right place to configure RDKit's …
=> feat: Enable Python logger for RDKit

visyn_core/sentry/sentry_integration.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Set profiles_sample_rate to 0 by default as it is now "Pay as you Go"
- It can always be enabled via the `visyn_core.sentry.backend_init_options`.
-  
=> feat: set Sentry profiles_sample_rate to 0

visyn_core/security/store/oauth2_security_store.py, visyn_core/settings/model.py, visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Previously, the OAuth2 security store was limited to consume tokens from a single headers. This is limiting if multiple headers may contain the relevant token (i.e. the access or ID token)
- Now, we can actually pass multiple token headers, falling back to the existing ones for full backwards compatibility.  
-  
=> feat: expand OAuth2 Security Store with ability to try multiple token headers

visyn_core/security/store/oauth2_security_store.py, visyn_core/settings/model.py, visyn_core/tests/test_security_login.py
**Issue**
**UI/UX/Vis**
**Code**
**PR**
- Previously, loading a user was aborted if an exception was thrown. Now it iterates through all user tokens even if exceptions are thrown.
- Adds `use_user_headers` to completely avoid decoding access tokens and use `X-Forwarded-Email` instead.
-  
=> fix: enable support for iterating through multiple headers even if exceptions are thrown
